import { defineConfig } from "vite-plus";

export default defineConfig({
  test: {
    setupFiles: ["./tests/cache-env.setup.ts"],
    coverage: {
      provider: "v8",
      reporter: [["text", { skipFull: false }]],
      include: ["packages/*/src/**/*.ts"],
      thresholds: {
        perFile: true,
        lines: 80,
        functions: 75,
        statements: 75,
        branches: 60,
      },
    },
  },
  fmt: {
    ignorePatterns: [
      "coverage/**",
      "dist/**",
      "pnpm-lock.yaml",
      ".agent/**",
      ".agents/**",
      ".claude/**",
      ".codex/**",
      ".continue/**",
      ".cursor/**",
      ".gemini/**",
      ".opencode/**",
      ".pi/**",
      ".roo/**",
      ".vite-hooks/**",
      ".windsurf/**",
      "scripts/oxlint/anti-slop/**",
    ],
    printWidth: 100,
    tabWidth: 2,
    useTabs: false,
  },
  lint: {
    ignorePatterns: [
      "coverage/**",
      "dist/**",
      ".agent/**",
      ".agents/**",
      ".claude/**",
      ".codex/**",
      ".continue/**",
      ".cursor/**",
      ".gemini/**",
      ".opencode/**",
      ".pi/**",
      ".roo/**",
      ".vite-hooks/**",
      ".windsurf/**",
      "scripts/oxlint/anti-slop/**",
    ],
    jsPlugins: [
      { name: "vite-plus", specifier: "vite-plus/oxlint-plugin" },
      { name: "anti-slop", specifier: "./scripts/oxlint/anti-slop/index.ts" },
    ],
    rules: {
      "vite-plus/prefer-vite-plus-imports": "error",
      "anti-slop/no-chained-type-assertions": "error",
      "anti-slop/no-conditional-empty-object-spread": "error",
      "anti-slop/no-known-value-widening": "error",
      "anti-slop/no-module-mocking": "error",
      "anti-slop/no-object-parameters": "error",
      "anti-slop/no-reflect-apply": "error",
      "anti-slop/no-reflect-get": "error",
      "anti-slop/no-runtime-typeof": ["error", { allowInTypeGuards: true }],
      "anti-slop/no-shape-in-symbol-names": "error",
      "anti-slop/no-unknown-parameters": "error",
      "anti-slop/no-unknown-returns": "error",
      "anti-slop/no-unknown-type-aliases": "error",
      "anti-slop/no-unsafe-dictionary-type": "error",
      "anti-slop/no-widen-then-assert": "error",
      "anti-slop/require-safety-comment-for-type-assertion": "error",
    },
    options: {
      typeAware: true,
      typeCheck: true,
    },
  },
  staged: {
    "*": "vp check --fix",
  },
});
