export const FETCH_DEFAULT_OFFSET = 0;
export const FETCH_MIN_MAX_CHARACTERS = 1_000;
export const FETCH_DEFAULT_MAX_CHARACTERS = 6_000;
export const FETCH_MAX_CHARACTERS = 30_000;
export const FETCH_MAX_OFFSET_CHARACTERS = 20_000_000;
export const FETCH_MAX_URL_CHARACTERS = 2_048;
